openapi: 3.0.0
info:
  description: >-
    Zulutex is a cryptocurrency payment API.<br><br>It is designed with the
    intent to allow you to integrate multiple coin payments in your service with
    the least effort possible.<br><br>There are no sign-ups, lengthy
    implementations or API keys required, it is as easy as a simple CURL request
    to create a new payment address.<br><br>The only thing required is that you
    implement the logic on your server to handle the callbacks sent to your
    server when the transaction from the client is confirmed.
  version: v1.0.0
  title: Zulutex - Payment API Documentation
  contact:
    email: support@zulutex.com
  x-logo:
    url: https://zulutex.com/static/assets/images/300_logo_ca.png
servers:
  - url: https://api.zulutex.com
  - url: https://api-dev.zulutex.com
tags:
  - name: Payments
    description: Endpoints to create payments.
paths:
  /{ticker}/create/:
    get:
      tags:
        - Receive a payment
      summary: Create new address
      description: >-
        This method is used to generate a new address to give your clients,
        where they can send payments.<br><br>**Notice:** The length of this
        request can't surpass the ```8192``` characters!<br/><br/> ***Please
        make sure when sending a transaction you <a
        href="https://zulutex.com/cryptocurrencies/" target="_blank">consult the
        minimum transfer value</a> for the crypto/token you wish to use. If the
        value you send is bellow our minimums, Zulutex will ignore the
        transaction.***<br/><br/> Before delving into the documentation, why not
        check if the <a href="https://zulutex.com/libraries/"
        target="_blank">libraries</a> already have the functionality you need?
        It could save you time and effort in the long run!
      operationId: create
      parameters:
        - in: path
          name: ticker
          description: >-
            The token ticker. Currently supported tokens can be checked on the
            **<a href="https://zulutex.com/cryptocurrencies/"
            target="_blank">Supported Coins page</a>**.
          required: true
          schema:
            type: string
        - in: query
          name: callback
          description: >-
            The URL the callbacks will be sent to. Must be a valid
            URL.<br><br>**Attention:**<br><br>- The callback URL should be
            unique. Duplicated callback URLs will return the same `address_in`.
            You can make your callback URL unique by adding GET parameters,
            like: `?user_id=1234`<br><br>- The callback URL needs to be
            `urlencoded`, otherwise the GET parameters you add may be lost.
          required: true
          schema:
            type: string
        - in: query
          name: address
          description: >-
            Address or addresses where the payment will be forwarded to.<br><br>
            In case of multiple addresses, it should be in the following format:
            `<percentage_1>@<address_1>|<percentage_2>@<address_2>` and so
            on.<br><br>Percentages are set from 0.0001 (0.01%) to 1.0 (100%) and
            must add up to 1.00 (100%).<br><br> Addresses must be
            valid.<br><br>**Note:** For multiple addresses the minimum value per
            transaction (**<a href='https://zulutex.com/cryptocurrencies/'
            target='blank'>see cryptocurrencies page</a>**) is multiplied by the
            following formula: 1 + (N - 1) / 3, where N is the number of output
            addresses. <br/><br/>**Check our <a
            href="https://support.zulutex.com/article/multi-address-minimums"
            target="_blank">knowledge base</a> for more information about
            multi-address minimums.**
          schema:
            type: string
        - in: query
          name: pending
          description: >-
            Set this to 1 if you want to be notified of pending transactions
            (before they're confirmed)
          required: false
          schema:
            type: integer
        - in: query
          name: confirmations
          description: >-
            Number of confirmations you want before receiving the callback (Min.
            1)
          required: false
          schema:
            type: integer
        - in: query
          name: email
          description: >-
            E-mail address to receive payment notifications<br><br>**Note:
            before getting e-mail payment notifications, you must confirm your
            e-mail address <a href='https://zulutex.com/confirm_email/'
            target='_blank'>here</a>.**
          required: false
          schema:
            type: string
        - in: query
          name: post
          description: >-
            Set this to 1 if you wish to receive the callback as a POST request
            (default: GET)
          required: false
          schema:
            type: integer
        - in: query
          name: priority
          description: >-
            Different per currency/network.<br/><br/>**Check our <a
            href="https://support.zulutex.com/article/how-the-priority-parameter-works"
            target="_blank">knowledge base</a> for more information about this
            parameter.**
          required: false
          schema:
            type: string
        - in: query
          name: multi_token
          description: >-
            Set this to 1 to enable it (default: 0).<br><br>**Check our <a
            href="https://support.zulutex.com/article/how-the-multi_token-parameter-works"
            target="_blank">knowledge base</a> for more information about this
            parameter.**
          required: false
          schema:
            type: integer
        - in: query
          name: multi_chain
          description: >-
            Set this to 1 to enable it (default: 0).<br><br> **Check our <a
            href="https://support.zulutex.com/article/how-the-multi_chain-parameter-works"
            target="_blank">knowledge base</a> for more information about this
            parameter.**
          required: false
          schema:
            type: integer
        - in: query
          name: convert
          description: >-
            Set this to 1 to enable it (default: 0).<br><br> If enabled, returns
            the converted value converted to FIAT in the callback, with the
            parameters ``value_coin_convert`` and
            ``value_forwared_coin_convert``. The value of the fields are
            json-encoded.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Address was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create'
        '400':
          description: Error creating address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
