version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "127.0.0.1:8000:8080"
    volumes:
      - ./api.yaml:/usr/share/nginx/html/api.yaml
    environment:
      API_URL: api.yaml
